# Configuration for Ensemble emotion recognition model (joint training)

model:
  type: "ensemble"
  models:
    - type: "distilbert"
      model_name: "distilbert-base-uncased"
      weight: 0.4
    - type: "twitter_roberta"
      model_name: "cardiffnlp/twitter-roberta-base-emotion"
      weight: 0.4
    - type: "bilstm"
      weight: 0.2
  num_classes: 6
  voting_strategy: "soft"  # Options: soft, hard
  dropout_rate: 0.3
  max_length: 128

training:
  # Ensemble training strategy
  strategy: "joint"  # Options: individual, joint
  batch_size: 16
  learning_rate: 1e-5
  num_epochs: 5
  warmup_steps: 200
  weight_decay: 0.01
  gradient_clip_norm: 1.0

# Data and preprocessing
# (copied from previous ensemble config for consistency)
data:
  max_length: 128
  text_column: "text"
  label_column: "label"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_sizes:
    train: 16
    validation: 32
    test: 32
  shuffle:
    train: true
    validation: false
    test: false
  num_workers: 0

preprocessing:
  adaptive: true
  lowercase: true
  remove_urls: true
  remove_mentions: true
  remove_hashtags: false
  remove_extra_whitespace: true
  remove_stopwords: false
  expand_contractions: true
  emoji_handling: "convert"
  add_special_tokens: true

evaluation:
  metrics:
    - "accuracy"
    - "f1_macro"
    - "f1_weighted"
    - "precision_macro"
    - "recall_macro"
    - "roc_auc"
  evaluate_individual: true
  plot_confusion_matrix: true
  plot_training_history: true
  plot_embeddings: true
  save_predictions: true
  plot_ensemble_analysis: true

paths:
  data_dir: "data"
  model_dir: "models"
  output_dir: "outputs"
  log_dir: "logs"
  cache_dir: "cache"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

device:
  auto_detect: true
  force_cpu: false

# Emotion labels (must match dataset)
emotions:
  - "sadness"
  - "joy"
  - "love"
  - "anger"
  - "fear"
  - "surprise"
