# Configuration for Ensemble emotion recognition model

model:
  type: "ensemble"
  models:
    - type: "distilbert"
      model_name: "distilbert-base-uncased"
      weight: 0.5 # Adjusted weight
    - type: "twitter-roberta"
      model_name: "cardiffnlp/twitter-roberta-base-emotion"
      weight: 0.5 # Adjusted weight
  
  num_classes: 6
  voting_strategy: "soft"  # Options: soft, hard
  dropout_rate: 0.3
  max_length: 128

training:
  # Ensemble training strategy
  strategy: "joint"  # Changed to joint for potentially faster/better optimization
  
  # Individual model training (paths for individual models if strategy were "individual")
  individual_configs:
    - "configs/distilbert_config.yaml"
    - "configs/twitter_roberta_config.yaml"
  
  # Joint training (if strategy is "joint")
  batch_size: 32 # Potentially increase if memory allows
  learning_rate: 2e-5 # Adjusted, common for transformers
  num_epochs: 5
  warmup_steps: 200
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  mixed_precision: true # Ensure this is true for AMP
  device: "auto" # Auto-detect device or specify "cpu" or "cuda"
  loss_type: "cross_entropy" # or focal
  # focal_loss_gamma: 2.0 # if loss_type is focal
  # label_smoothing: 0.0 # if needed

data:
  max_length: 128
  text_column: "text"
  label_column: "label"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  
  # Data loading
  batch_sizes:
    train: 32 # Ensure this matches training.batch_size
    validation: 32
    test: 32
  
  shuffle:
    train: true
    validation: false
    test: false
  
  num_workers: 4 # Ensure this is set, was 0 in attachment

preprocessing:
  # Use preprocessing optimized for each model
  adaptive: true
  
  # Default preprocessing (when not adaptive)
  lowercase: true
  remove_urls: true
  remove_mentions: true
  remove_hashtags: false
  remove_extra_whitespace: true
  remove_stopwords: false
  expand_contractions: true
  
  # Emoji handling
  emoji_handling: "convert"
  
  # Special tokens
  add_special_tokens: true

evaluation:
  metrics:
    - "accuracy"
    - "f1_macro"
    - "f1_weighted"
    - "precision_macro"
    - "recall_macro"
    - "roc_auc"
  
  # Individual model evaluation
  evaluate_individual: true
  
  # Visualization options
  plot_confusion_matrix: true
  plot_training_history: true
  plot_embeddings: true
  save_predictions: true
  plot_ensemble_analysis: true

paths:
  data_dir: "data"
  model_dir: "models"
  output_dir: "outputs"
  log_dir: "logs"
  cache_dir: "cache"
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
device:
  # Auto-detect device or specify manually
  auto_detect: true
  force_cpu: false
  
# Emotion labels (must match dataset)
emotions:
  - "sadness"
  - "joy"
  - "love"
  - "anger"
  - "fear"
  - "surprise"
